[package]
name = "proto_terraform"
version = "0.1.0"
edition = "2024"
description = "Terraform WASM plugin for proto."
authors = ["ageha734"]
license = "MIT"
repository = "https://github.com/ageha734/proto-terraform"
publish = false

[features]
default = []
wasm = []

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
proto_pdk = "0.35.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
proto_pdk_test_utils = "0.50.0"
starbase_sandbox = "0.12.0"
tokio = { version = "1.51.1", features = ["full"] }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
