name: "[Reusable] Release"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.tag }}
          persist-credentials: false

      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: proto_terraform.wasm
          path: .

      - name: Rename WASM for proto github:// loader
        run: |
          mv proto_terraform.wasm terraform.wasm
          sha256sum terraform.wasm > terraform.wasm.sha256

      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          tag_name: ${{ inputs.tag }}
          draft: true
          files: |
            terraform.wasm
            terraform.wasm.sha256
          prerelease: ${{ contains(inputs.tag, '-alpha.') }}
          generate_release_notes: true

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.tag }}
        run: gh release edit "$TAG" --draft=false
